### ISSUE TITLE
Total vaccinations

### ISSUE THREAD

**Issue by rcsmit** [Sikerdebaard/vaccinatie-orakel#1]
Wat is  "Total vaccinations" in https://github.com/Sikerdebaard/vaccinatie-orakel/blob/main/data/ensemble.csv ? De waardes zijn hoger dan het aantal inwoners in NL.

**Comment by Sikerdebaard** [comment]
https://github.com/Sikerdebaard/vaccinatie-orakel#dataensemblecsv

![image](https://user-images.githubusercontent.com/801853/122673996-8c795a80-d1d3-11eb-961f-090da859e6d8.png)

Met 13.791.512 doses is dit zeer zeker nog niet hoger dan het aantal inwoners in NL maar deze twee cijfers zijn dan ook niet aan elkaar gerelateerd. Aantal doses gezet / total_vaccinations staat namelijk niet gelijk aan het aantal mensen dat gevaccineerd zijn.

**Comment by rcsmit** [comment]
Kijk ik dan verkeerd? Regel 2 is 101,5 mln

 https://imgur.com/gallery/fr1GTEK

**Comment by Sikerdebaard** [comment]
Hmm dat ziet er wel wat vreemd uit inderdaad. * duikt in de code *

**Comment by Sikerdebaard** [comment]
Dit lijkt te komen door deze regel code: https://github.com/Sikerdebaard/vaccinatie-orakel/blob/main/src/scrapers/yorickb.py#L46

Ik kijk er morgen even verder naar, het is op dit moment wat druk. Mocht je de data nu direct nodig hebben dan kan je die hier vinden: https://github.com/Sikerdebaard/netherlands-vaccinations-scraper/blob/main/vaccine_administered_total.csv  col estimated

**Comment by Sikerdebaard** [comment]
@rcsmit de code en csv is aangepast. Laat het even weten als je nog ergens tegenaan loopt.
